(() => {
  const S=HermesStore, V=HermesViews, {icon,esc}=V;
  const $=(q,root=document)=>root.querySelector(q);
  const $$=(q,root=document)=>[...root.querySelectorAll(q)];
  const ui={page:new URLSearchParams(location.search).get('view')==='workspace'?'workspace':'home',menu:false,aiHidden:false,aiDrawer:false,aiTab:'chat',taskFilter:'pending',moduleFilter:'all',moduleQuery:'',runFilter:'all',workspaceTab:'code',file:'code',split:false,showDiff:false,codeDraft:S.data.code,noteDraft:S.data.note,codeDirty:false,noteDirty:false,chat:[],running:false,terminalLog:'$ hermes workspace status\nLocal preview ready. No runtime connected.'};
  ui.healthTab='sleep';ui.agentTab='models';ui.calendarDay='2026-09-18';
  let focusBeforeModal=null,toastTimer,runTimer;
  function icons(){lucide.createIcons({attrs:{'stroke-width':1.7}});}
  function render(){
    $('#app').innerHTML=V.shell(ui);icons();document.title=`${V.names[ui.page]} · Hermes`;
    const range=`${S.data.planStart||'15:00'} – ${S.data.planEnd||'16:30'}`;
    $$('.plan-step strong').forEach(el=>{if(el.textContent.includes('15:00 – 16:30'))el.textContent=`${range} · 专注产品方案`;});
    const focusEvent=$('[data-event="focus"]');if(focusEvent){focusEvent.parentElement.querySelector('span').textContent=S.data.planStart||'15:00';focusEvent.querySelector('small').innerHTML=`${icon('headphones')}${planMinutes()} 分钟 · ${S.data.planApproved?'已安排':'建议时段'}`;icons();}
    const focusSummary=$('.summary-item[data-page="workspace"] .summary-number');
    if(focusSummary)focusSummary.innerHTML=`${Number((1.5+(S.data.planApproved?planMinutes()/60:0)).toFixed(2))}<small>小时</small>`;
    const planDescription=$$('.plan-step p')[1];if(planDescription)planDescription.textContent=`避开会议，保留 ${planMinutes()} 分钟完整时间`;
    if(S.data.codeApplied){const intro=$$('.ai-intro p')[1];if(intro)intro.textContent='登录问题的示例修复已应用到本地草稿。你可以继续检查代码，或者把下午留给产品方案。';const step=$('.plan-step strong');if(step)step.textContent='登录问题的示例修复已应用';}
    const modelLabel=$('.model-label');if(modelLabel){const control=document.createElement('button');control.type='button';control.className='model-label model-picker';control.dataset.action='models';control.setAttribute('aria-label','选择 Hermes 模型');control.textContent=S.data.agent.model||'选择模型';modelLabel.replaceWith(control);control.insertAdjacentHTML('beforebegin',`<button type="button" class="icon-button" data-action="voice" aria-label="语音对话" data-tooltip="语音对话">${icon('mic')}</button>`);icons();}
    $$('.task-row').forEach(row=>{const id=$('[data-task-toggle]',row)?.dataset.taskToggle;const t=S.data.tasks.find(t=>t.id===id);if(t?.scheduledAt){const meta=$('.task-meta',row);meta?.insertAdjacentHTML('beforeend',`<span class="task-calendar-link">${icon('calendar')}${esc(t.scheduledAt.slice(5,10))} ${esc(t.scheduledAt.slice(11,16))}</span>`);}});icons();
  }
  function planMinutes(){const toMinutes=t=>Number(t.slice(0,2))*60+Number(t.slice(3));return toMinutes(S.data.planEnd||'16:30')-toMinutes(S.data.planStart||'15:00');}
  function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3300);}
  function save(){if(!S.save())toast('浏览器存储不可用，修改仅保留在当前窗口');}
  function closeModal(){HermesVoice.stop();const previous=focusBeforeModal;$('#modal-root').innerHTML='';if(previous?.isConnected)previous.focus();}
  function modal(title,body,large=false){HermesVoice.stop();focusBeforeModal=document.activeElement;$('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal ${large?'large':''}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-header"><h2 id="modal-title">${title}</h2><button class="icon-button" data-action="close-modal" aria-label="关闭">${icon('x')}</button></header>${body}</section></div>`;
    const taskForm=$('#task-form');if(taskForm){const task=S.data.tasks.find(t=>t.id===taskForm.dataset.id);$('.modal-actions',taskForm).insertAdjacentHTML('beforebegin',`<div class="setting-row" style="margin-bottom:17px"><div><strong>安排到日历</strong><p>完成状态与待办保持一致</p></div><input type="checkbox" id="task-scheduled" name="scheduled" aria-label="安排到日历" ${task?.scheduledAt||ui.page==='calendar'?'checked':''}></div><div class="form-row"><div class="form-field"><label for="task-date">安排日期</label><input id="task-date" name="date" type="date" value="${task?.scheduledAt?.slice(0,10)||ui.calendarDay}" required></div><div class="form-field"><label for="task-time">开始时间</label><input id="task-time" name="start" type="time" value="${task?.scheduledAt?.slice(11,16)||'16:30'}" required></div></div>`);}
    icons();($('.modal input:not([type="checkbox"]),.modal textarea')||$('.modal button'))?.focus();}
  function navigate(page){if(!V.names[page])return;ui.page=page;ui.menu=false;closeModal();render();window.scrollTo({top:0,behavior:'instant'});}
  function openWorkspace(tab='code',review=false){ui.workspaceTab=tab;ui.showDiff=review;ui.page='workspace';ui.menu=false;closeModal();render();window.scrollTo({top:0,behavior:'instant'});}
  const buttons=(label='保存')=>`<div class="modal-actions"><button class="secondary" type="button" data-action="close-modal">取消</button><button class="primary" type="submit">${icon('check')}${label}</button></div>`;
  function taskModal(id){const t=S.data.tasks.find(t=>t.id===id);modal(t?'编辑任务':'交办一件事',`<form id="task-form" data-id="${t?.id||''}"><div class="form-field"><label for="task-title">任务名称</label><input id="task-title" name="title" placeholder="接下来想完成什么？" value="${esc(t?.title||'')}" required maxlength="120"></div><div class="form-row"><div class="form-field"><label for="task-project">工作空间</label><select id="task-project" name="project">${['个人工作台','Hermes App','设计探索','个人成长'].map(p=>`<option ${p===t?.project?'selected':''}>${p}</option>`).join('')}</select></div><div class="form-field"><label for="task-minutes">预估时长（分钟）</label><input id="task-minutes" type="number" name="minutes" min="5" max="480" step="5" value="${t?.minutes||30}" required></div></div><div class="form-field"><label for="task-priority">优先级</label><select id="task-priority" name="priority"><option value="normal">普通</option><option value="high" ${t?.priority==='high'?'selected':''}>高优先级</option></select></div><div class="modal-actions">${t?`<button class="text-button danger" type="button" data-task-delete="${t.id}" style="margin-right:auto">删除任务</button>`:''}<button class="secondary" type="button" data-action="close-modal">取消</button><button class="primary" type="submit">${icon('check')}${t?'保存修改':'创建任务'}</button></div></form>`);}
  function moduleModal(id){const m=S.data.modules.find(m=>m.id===id);if(!m)return;const permissions=m.type==='Skill'?['访问用户选择的任务上下文','提出计划，不自动获得执行权限']:m.id==='health'?['读取经授权的健康摘要','模型访问健康信息需单独授权']:['读取用户选择的数据范围','修改操作需另行授权'];modal(esc(m.name),`<div class="module-detail-top">${V.moduleIcon(m)}<div><p>${esc(m.desc)}</p><span class="tag">${esc(m.type)} · ${esc(m.status)}</span></div></div><h3 style="font-size:12px">能力与访问范围</h3><div class="permission-list">${permissions.map(p=>`<span>${icon('shield-check')}${p}</span>`).join('')}</div>${m.endpoint?`<p class="modal-description">服务地址：${esc(m.endpoint)}</p>`:''}<p class="modal-description">当前仅保存能力配置。真实 ${m.type==='Skill'?'技能执行':'服务连接'}尚未接入，不会读取外部账户数据。</p><div class="modal-actions">${m.installed?`<button class="text-button danger" data-module-remove="${m.id}" style="margin-right:auto">移除能力</button><button class="secondary" data-action="close-modal">关闭</button><button class="primary" data-module-config="${m.id}">连接配置</button>`:`<button class="secondary" data-action="close-modal">取消</button><button class="primary" data-module-install="${m.id}">${icon('plus')}添加到工作台</button>`}</div>`);}
  function moduleConfig(id){const m=S.data.modules.find(m=>m.id===id);modal(`${esc(m.name)} · 配置`,m.type==='MCP'?`<form id="module-config-form" data-id="${m.id}"><div class="form-field"><label for="endpoint">MCP 服务地址</label><input id="endpoint" name="endpoint" type="url" placeholder="https://example.com/mcp" value="${esc(m.endpoint||'')}" required></div><p class="modal-description">地址仅保存在本地。本预览不会连接服务或收集密钥。</p>${buttons('保存配置')}</form>`:`<p class="modal-description">${m.type==='Skill'?'技能运行环境':m.id==='health'?'移动端健康授权':'OAuth 登录与授权'}尚未接入。添加的能力已保留在你的工作台中。</p><div class="detail-list"><div>${icon('shield-check')}未读取外部账户数据</div><div>${icon('hard-drive')}当前配置仅保存在本地</div></div><div class="modal-actions"><button class="primary" data-action="close-modal">完成</button></div>`);}
  function login(){modal('个人账户',`<div class="login-brand"><span class="brand-mark">${icon('asterisk')}</span>hermes</div><p class="login-caption">一个空间，连接你的工作与生活。<br><span class="tag">登录流程预览 · 无真实认证</span></p><form id="login-form"><div class="form-field"><label for="login-name">演示昵称</label><input id="login-name" name="name" value="${esc(S.data.user.name)}" required maxlength="40"></div><div class="form-field"><label for="login-email">演示邮箱</label><input id="login-email" name="email" type="email" value="${esc(S.data.user.email)}" required></div><p class="modal-description">此处只切换演示身份，数据仍在当前浏览器中。请勿输入真实密码或其他凭据。</p><div class="modal-actions">${S.data.user.signedIn?'<button type="button" class="text-button" data-action="sign-out" style="margin-right:auto">退出演示账户</button>':''}<button type="submit" class="primary">${icon('arrow-right')}进入演示工作空间</button></div></form>`);}
  function calendar(){modal('9 月 18 日，星期五',`<p class="modal-description">个人日历 · 本地演示</p><div class="detail-list"><div>${icon('video')}14:00 – 14:45 · 产品项目周会</div>${S.data.planApproved?`<div>${icon('headphones')}${S.data.planStart||'15:00'} – ${S.data.planEnd||'16:30'} · 专注产品方案</div>`:''}<div>${icon('footprints')}18:30 – 19:00 · 下班后的散步</div>${S.data.calendar.filter(e=>e.id!=='plan').map(e=>`<div>${icon('calendar')}${esc(e.time)} · ${esc(e.title)}</div>`).join('')}</div><div class="modal-actions"><button class="secondary" data-action="new-event">${icon('plus')}新增日程</button><button class="primary" data-action="close-modal">完成</button></div>`);}
  function reviewCode(){ui.showDiff=true;openWorkspace('code',true);}
  function runDetail(id){const r=S.data.executions.find(r=>r.id===id);if(!r)return;if(r.kind==='code'){reviewCode();return;}if(r.kind==='plan'){calendar();return;}modal(esc(r.title),`<p class="modal-description">${esc(r.detail)} · 演示产物</p><div class="detail-list"><div>${icon('circle-check')}回顾了 2 个工作空间</div><div>${icon('list-todo')}梳理了下周优先事项</div></div><p class="modal-description" style="margin-top:20px">这是一份示例执行记录，不代表真实的 AI 后台运行。</p><div class="modal-actions"><button class="secondary" data-action="close-modal">关闭</button><button class="primary" data-workspace="note">打开关联文档</button></div>`);}
  function search(){modal('搜索工作空间',`<div class="search-field">${icon('search')}<input id="search-input" aria-label="搜索内容" placeholder="任务、工作空间、工具…" autocomplete="off"></div><div class="search-results" id="search-results"></div>`,true);searchResults('');}
  function searchResults(query){const q=query.trim().toLowerCase();const entries=[...S.data.tasks.map(t=>({title:t.title,type:'任务',icon:'circle-check',attr:`data-task-edit="${t.id}"`})),...S.data.modules.map(m=>({title:m.name,type:m.type,icon:m.icon,attr:`data-module="${m.id}"`})),{title:'Hermes App',type:'工作空间',icon:'code-xml',attr:'data-workspace="code"'},{title:'个人工作台产品方案',type:'文档',icon:'file-text',attr:'data-workspace="note"'},...Object.entries(V.names).map(([key,title])=>({title,type:'页面',icon:'arrow-up-right',attr:`data-page="${key}"`}))].filter(e=>e.title.toLowerCase().includes(q));$('#search-results').innerHTML=entries.slice(0,12).map(e=>`<button class="search-result" ${e.attr}>${icon(e.icon)}<span>${esc(e.title)}</span><small>${e.type}</small></button>`).join('')||'<div class="empty-state">没有匹配的内容</div>';icons();}
  function approvePlan(){if(!S.data.planApproved){const t=S.data.tasks.find(t=>t.id===(S.data.planTaskId||'t1'))||S.data.tasks.find(t=>!t.done);if(!t){toast('先添加一个待办，再安排专注时间');return;}const start=`2026-09-18T${S.data.planStart||'15:00'}`;if(hasConflict(start,planMinutes(),t.id)){toast('这个时间段已有安排，请先调整时间');return;}S.data.planApproved=true;S.data.planTaskId=t.id;t.scheduledAt=start;t.minutes=planMinutes();S.data.calendar=S.data.calendar.filter(e=>e.id!=='plan');S.data.executions=S.data.executions.filter(r=>r.id!=='plan');S.data.executions.unshift({id:'plan',title:'安排下午专注时间',detail:'个人日历 · 关联待办',kind:'plan',status:'complete',time:'11:24'});save();}closeModal();render();toast('已安排到日历；任务进度与日历同步');}
  function hasConflict(start,minutes,exclude){const date=start.slice(0,10),begin=Number(start.slice(11,13))*60+Number(start.slice(14,16)),end=begin+minutes;if(end>1440)return true;const busy=S.data.tasks.filter(t=>t.id!==exclude&&t.scheduledAt?.startsWith(date)).map(t=>[Number(t.scheduledAt.slice(11,13))*60+Number(t.scheduledAt.slice(14,16)),t.minutes]);if(date==='2026-09-18'){busy.push([840,45],[1110,30]);S.data.calendar.filter(e=>e.id!=='plan').forEach(e=>busy.push([Number(e.time.slice(0,2))*60+Number(e.time.slice(3)),30]));}return busy.some(([b,d])=>begin<b+d&&end>b);}
  function reconcilePlan(task){if(task.id!==(S.data.planTaskId||'t1')||!S.data.planApproved)return;if(!task.scheduledAt?.startsWith('2026-09-18')){S.data.planApproved=false;S.data.executions=S.data.executions.filter(r=>r.id!=='plan');return;}S.data.planStart=task.scheduledAt.slice(11,16);const end=Number(S.data.planStart.slice(0,2))*60+Number(S.data.planStart.slice(3))+task.minutes;S.data.planEnd=`${String(Math.floor(end/60)).padStart(2,'0')}:${String(end%60).padStart(2,'0')}`;}
  function applyCode(){if(ui.codeDraft!==S.baseline&&ui.codeDraft!==S.patched){toast('代码已被编辑。请先保存并手动合并，避免覆盖你的修改');return;}S.data.code=S.patched;S.data.codeApplied=true;ui.codeDraft=S.patched;ui.codeDirty=false;const run=S.data.executions.find(r=>r.id==='r1');if(run)run.status='complete';save();render();toast('已应用到本地代码示例，未修改真实仓库');}
  function saveWorkspace(){S.data.code=ui.codeDraft;S.data.note=ui.noteDraft;ui.codeDirty=false;ui.noteDirty=false;save();render();toast('代码与文档草稿已保存到本地');}
  function runCheck(){if(ui.running)return;ui.running=true;ui.terminalLog='$ preview check\n[simulation] Loading sample workspace…';render();runTimer=setTimeout(()=>{ui.terminalLog='$ preview check\n[simulation] Reading local draft…\n[simulation] Workflow completed.\nNo real compiler or tests were executed.';ui.running=false;render();toast('演示检查流程完成；未运行真实测试');},1200);}
  function action(name){switch(name){
    case 'models':ui.agentTab='models';navigate('agent');break;
    case 'calendar-today':ui.calendarDay='2026-09-18';render();break;
    case 'voice':modal('和 Hermes 说话',`<div class="voice-surface"><div class="voice-symbol" id="voice-symbol">${icon('audio-lines')}</div><h3 id="voice-status" role="status" aria-live="polite">准备好后，开始说话</h3><p id="voice-transcript">${HermesVoice.recognitionAvailable?'系统语音识别 · 点击后请求麦克风权限':'当前浏览器不支持语音识别，可尝试系统朗读'}</p></div><div class="setting-row"><div><strong>连续对话</strong><p>回复后继续聆听，关闭窗口即停止</p></div><input type="checkbox" id="voice-continuous" aria-label="连续对话模式" ${S.data.agent.voice.continuous?'checked':''}></div><div class="form-field" style="margin-top:18px"><label for="voice-choice">朗读语音</label><select id="voice-choice">${HermesFeatures.voiceOptions()}</select></div><p class="modal-description">当前为本地演示回复，未连接 Hermes。浏览器识别可能依赖在线服务。</p><div class="modal-actions"><button class="secondary" data-action="voice-preview">${icon('volume-2')}试听</button><button class="secondary" data-action="voice-stop">${icon('square')}停止</button><button class="primary" data-action="voice-start" ${HermesVoice.recognitionAvailable?'':'disabled'}>${icon('mic')}开始说话</button></div>`);break;
    case 'voice-start':S.data.agent.voice.continuous=!!$('#voice-continuous')?.checked;S.data.agent.voice.voice=$('#voice-choice')?.value||'';save();HermesVoice.start({continuous:S.data.agent.voice.continuous});break;
    case 'voice-stop':HermesVoice.stop();break;
    case 'voice-preview':{HermesVoice.stop();const settings={...S.data.agent.voice,voice:$('#voice-choice')?.value||'',rate:Number($('#voice-rate')?.value||S.data.agent.voice.rate)};if(!HermesVoice.speak('你好，我是 Hermes。让我们一起，把重要的事情做好。',settings))toast('当前系统没有可用的朗读语音');break;}
    case 'new-schedule':modal('新建定时规则',`<form id="schedule-form"><div class="form-field"><label for="schedule-name">规则名称</label><input id="schedule-name" name="name" required maxlength="80" placeholder="每周工作回顾"></div><div class="form-row"><div class="form-field"><label for="schedule-when">重复</label><select id="schedule-when" name="when"><option>每天</option><option>工作日</option><option>每周五</option><option>每周日</option></select></div><div class="form-field"><label for="schedule-time">时间</label><input id="schedule-time" name="time" type="time" value="18:00" required></div></div><div class="form-field"><label for="schedule-prompt">交给 Hermes 的任务</label><textarea id="schedule-prompt" name="prompt" rows="4" required maxlength="4000" placeholder="汇总本周已完成任务，整理下周重点。"></textarea></div><p class="modal-description">时区：Asia/Shanghai。规则仅保存在本地，尚未连接后台调度。</p>${buttons('保存规则')}</form>`);break;
    case 'close-modal':closeModal();break;
    case 'menu':ui.menu=!ui.menu;render();break;
    case 'close-menu':ui.menu=false;render();break;
    case 'toggle-ai':if(innerWidth<=1080){ui.aiDrawer=!ui.aiDrawer;ui.aiHidden=false;}else ui.aiHidden=!ui.aiHidden;render();break;
    case 'new-task':taskModal();break;
    case 'search':search();break;
    case 'login':login();break;
    case 'sign-out':S.data.user.signedIn=false;save();closeModal();render();toast('已退出演示身份；本地数据保留');break;
    case 'space':navigate('account');break;
    case 'health-source':moduleModal('health');break;
    case 'context':ui.aiTab='context';ui.aiHidden=false;if(innerWidth<=1080)ui.aiDrawer=true;render();break;
    case 'calendar':case 'view-plan':navigate('calendar');break;
    case 'new-window':{saveWorkspace();const url=new URL(location.href);url.searchParams.set('view','workspace');const opened=window.open(url.href,'_blank','popup,width=1280,height=880');if(opened)toast('已打开独立工作窗口，共享本地工作空间');else toast('弹出窗口被浏览器拦截，请允许此页面打开新窗口');break;}
    case 'split':ui.split=!ui.split;render();break;
    case 'diff':ui.showDiff=!ui.showDiff;render();break;
    case 'review-code':reviewCode();break;
    case 'save-workspace':saveWorkspace();break;
    case 'apply-code':applyCode();break;
    case 'run-check':runCheck();break;
    case 'approve-plan':approvePlan();break;
    case 'undo-plan':{const t=S.data.tasks.find(t=>t.id===(S.data.planTaskId||'t1'));if(t)t.scheduledAt='';S.data.planApproved=false;S.data.calendar=S.data.calendar.filter(e=>e.id!=='plan');S.data.executions=S.data.executions.filter(e=>e.id!=='plan');save();render();toast('已取消日历安排，待办仍然保留');break;}
    case 'adjust-plan':modal('调整专注时间',`<form id="plan-form"><p class="modal-description">9 月 18 日 · 现有会议 14:00 – 14:45，散步 18:30 – 19:00</p><div class="form-row"><div class="form-field"><label for="plan-start">开始时间</label><input id="plan-start" name="start" type="time" value="${S.data.planStart||'15:00'}" required></div><div class="form-field"><label for="plan-end">结束时间</label><input id="plan-end" name="end" type="time" value="${S.data.planEnd||'16:30'}" required></div></div>${buttons('更新建议')}</form>`);break;
    case 'new-event':modal('新增日程',`<form id="event-form"><p class="modal-description">9 月 18 日 · 本地日历</p><div class="form-field"><label for="event-title">日程名称</label><input id="event-title" name="title" required maxlength="100"></div><div class="form-field"><label for="event-time">开始时间</label><input id="event-time" name="time" type="time" value="16:30" required></div>${buttons('创建日程')}</form>`);break;
    case 'new-chat':ui.chat=[];render();toast('已开启新的演示对话');break;
    case 'summarize':ui.aiTab='chat';ui.aiHidden=false;if(innerWidth<=1080)ui.aiDrawer=true;ui.chat.push({role:'assistant',text:`还有 ${S.data.tasks.filter(t=>!t.done).length} 项待办，其中 ${S.data.tasks.filter(t=>!t.done&&t.priority==='high').length} 项高优先级。可先审阅代码修复，再推进产品方案。这是本地数据摘要，未调用模型。`});render();$('.chat-log')?.scrollTo(0,99999);break;
    case 'add-module':modal('添加你的能力',`<form id="add-module-form"><div class="form-field"><label for="module-name">名称</label><input id="module-name" name="name" placeholder="例如：我的知识库" required maxlength="50"></div><div class="form-row"><div class="form-field"><label for="module-type">能力类型</label><select id="module-type" name="type"><option>MCP</option><option>Skill</option><option>模块</option><option>连接器</option></select></div><div class="form-field"><label for="module-icon">图标</label><select id="module-icon" name="icon"><option value="database">数据库</option><option value="globe">网页</option><option value="code-xml">代码</option><option value="notebook">笔记</option><option value="blocks">模块</option></select></div></div><div class="form-field"><label for="module-desc">描述</label><textarea id="module-desc" name="desc" rows="2" maxlength="180" placeholder="这项能力可以帮你做什么？"></textarea></div><div class="form-field"><label for="module-endpoint">服务地址（可选）</label><input id="module-endpoint" name="endpoint" type="url" placeholder="https://example.com/mcp"></div><p class="modal-description">添加本地能力配置，不下载或执行外部代码。</p>${buttons('添加到工作台')}</form>`,true);break;
    case 'pair-device':modal('接续到另一台设备',`<p class="modal-description">演示配对流程 · 尚未建立真实设备连接</p><div class="device-code">482 916</div><form id="device-form"><div class="form-field"><label for="device-name">设备名称</label><input id="device-name" name="name" value="我的 Android 手机" maxlength="50" required></div><div class="modal-actions"><button type="button" class="secondary" data-action="close-modal">取消</button><button type="submit" class="primary">模拟添加设备</button></div></form>`);break;
    case 'notifications':modal('需要你留意的事',`<div class="notification-item">${icon('git-pull-request')}<div><strong>登录问题的示例修复${S.data.codeApplied?'已应用':'等待审阅'}</strong><p>Hermes App · session.ts</p><small>本地演示记录 · 11:18</small><button class="text-button" data-action="review-code">查看变更${icon('arrow-up-right')}</button></div></div><div class="notification-item">${icon('calendar')}<div><strong>今天的专注时间建议</strong><p>${S.data.planStart||'15:00'} – ${S.data.planEnd||'16:30'} · 个人工作台</p><small>${S.data.planApproved?'已保存到本地日历':'等待确认'}</small></div></div><div class="modal-actions"><button class="primary" data-action="close-modal">完成</button></div>`);break;
    case 'export':{const url=URL.createObjectURL(new Blob([JSON.stringify(S.data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='hermes-personal-workspace.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出工作空间数据');break;}
  }}
  document.addEventListener('click',event=>{
    if(event.target.classList.contains('modal-backdrop')){closeModal();return;}
    const el=event.target.closest('button,a,[data-action]');if(!el)return;
    const a=el.dataset;
    if(a.page){event.preventDefault();navigate(a.page);return;}
    if(a.action){action(a.action);return;}
    if(a.agentTab){ui.agentTab=a.agentTab;render();return;}
    if(a.calendarStep){const date=new Date(`${ui.calendarDay}T12:00:00`);date.setDate(date.getDate()+Number(a.calendarStep));ui.calendarDay=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;render();return;}
    if(a.unschedule){const t=S.data.tasks.find(t=>t.id===a.unschedule);t.scheduledAt='';reconcilePlan(t);save();render();toast('已取消安排，任务保留在待办中');return;}
    if(a.calendarEvent){const e=S.data.calendar.find(e=>e.id===a.calendarEvent);if(e)modal(esc(e.title),`<p class="modal-description">9 月 18 日 · ${esc(e.time)}</p><div class="modal-actions"><button class="secondary" data-calendar-delete="${esc(e.id)}">删除日程</button><button class="primary" data-action="close-modal">完成</button></div>`);else calendar();return;}
    if(a.calendarDelete){S.data.calendar=S.data.calendar.filter(e=>e.id!==a.calendarDelete);save();closeModal();render();return;}
    if(a.scheduleToggle){const s=S.data.agent.schedules.find(s=>s.id===a.scheduleToggle);s.enabled=!s.enabled;save();render();return;}
    if(a.scheduleDelete){S.data.agent.schedules=S.data.agent.schedules.filter(s=>s.id!==a.scheduleDelete);save();render();return;}
    if(a.taskToggle){const t=S.data.tasks.find(t=>t.id===a.taskToggle);t.done=!t.done;save();render();toast(t.done?'又完成了一件事':'已恢复为待完成');return;}
    if(a.taskEdit){taskModal(a.taskEdit);return;}
    if(a.taskDelete){const t=S.data.tasks.find(t=>t.id===a.taskDelete);t.scheduledAt='';reconcilePlan(t);S.data.tasks=S.data.tasks.filter(t=>t.id!==a.taskDelete);save();closeModal();render();toast('任务与关联日历安排已删除');return;}
    if(a.taskFilter){ui.taskFilter=a.taskFilter;render();return;}
    if(a.moduleFilter){ui.moduleFilter=a.moduleFilter;render();return;}
    if(a.runFilter){ui.runFilter=a.runFilter;render();return;}
    if(a.healthTab){ui.healthTab=a.healthTab;render();return;}
    if(a.aiTab){ui.aiTab=a.aiTab;render();return;}
    if(a.workspace){openWorkspace(a.workspace);return;}
    if(a.file){ui.file=a.file;render();return;}
    if(a.module){moduleModal(a.module);return;}
    if(a.moduleConfig){moduleConfig(a.moduleConfig);return;}
    if(a.moduleInstall){const m=S.data.modules.find(m=>m.id===a.moduleInstall);m.installed=true;m.status='待配置';save();closeModal();render();toast('能力已添加，尚未连接外部服务');return;}
    if(a.moduleRemove){const m=S.data.modules.find(m=>m.id===a.moduleRemove);m.installed=false;m.status='未添加';save();closeModal();render();toast('能力已移除');return;}
    if(a.removeDevice){S.data.devices=S.data.devices.filter(d=>d.id!==a.removeDevice);save();render();toast('演示设备已移除');return;}
    if(a.run){runDetail(a.run);return;}
    if(a.event){const title={meeting:'产品项目周会',focus:'专注 · 个人工作台',walk:'下班后的散步'}[a.event];const time={meeting:'14:00 – 14:45',focus:`${S.data.planStart||'15:00'} – ${S.data.planEnd||'16:30'}`,walk:'18:30 – 19:00'}[a.event];modal(title,`<div class="detail-list"><div>${icon('calendar')}2026 年 9 月 18 日，星期五</div><div>${icon('clock-3')}${time}</div><div>${icon('hard-drive')}本地演示${a.event==='focus'&&!S.data.planApproved?' · 建议时段，尚未安排':''}</div></div><div class="modal-actions"><button class="secondary" data-action="close-modal">关闭</button>${a.event==='focus'&&!S.data.planApproved?'<button class="primary" data-action="approve-plan">确认安排</button>':'<button class="primary" data-action="new-task">添加相关任务</button>'}</div>`);}
  });
  document.addEventListener('input',event=>{
    const el=event.target;
    if(el.id==='module-search'){ui.moduleQuery=el.value;$('#module-grid').innerHTML=V.moduleCards(ui);icons();}
    if(el.id==='search-input')searchResults(el.value);
    if(el.id==='voice-rate')$('#voice-rate-value').textContent=`${el.value}×`;
    if(el.id==='code-editor'&&ui.file==='code'){ui.codeDraft=el.value;ui.codeDirty=ui.codeDraft!==S.data.code;$('.editor-head span:last-child').textContent=ui.codeDirty?'未保存':'本地草稿';}
    if(el.id==='note-editor'){ui.noteDraft=el.value;ui.noteDirty=ui.noteDraft!==S.data.note;$('.note-pane .editor-head span:last-child').textContent=ui.noteDirty?'未保存':'本地文档';}
    el.setCustomValidity?.('');
  });
  document.addEventListener('change',event=>{if(event.target.id==='quiet-toggle'){S.data.quiet=event.target.checked;save();toast('个人偏好已保存');}if(event.target.dataset.toolToggle){S.data.agent.tools[event.target.dataset.toolToggle]=event.target.checked;save();toast('工具配置已保存，未改变真实系统权限');}});
  function requiredText(form,name){if(!form.elements[name].value.trim()){form.elements[name].setCustomValidity('请输入有效内容');form.elements[name].reportValidity();return false;}return true;}
  function validUrl(form,name){const value=form.elements[name].value.trim();if(!value)return true;try{const u=new URL(value);if(['http:','https:'].includes(u.protocol))return true;}catch{}form.elements[name].setCustomValidity('仅支持 HTTP 或 HTTPS 服务地址');form.elements[name].reportValidity();return false;}
  document.addEventListener('submit',event=>{
    event.preventDefault();const form=event.target,d=Object.fromEntries(new FormData(form));
    if(form.id==='task-form'){if(!requiredText(form,'title'))return;const task={title:d.title.trim(),project:d.project,priority:d.priority,minutes:Number(d.minutes),scheduledAt:d.scheduled?`${d.date}T${d.start}`:''};if(task.scheduledAt&&hasConflict(task.scheduledAt,task.minutes,form.dataset.id)){toast('该时段与已有安排冲突，或超出当天，请调整');return;}if(form.dataset.id){const t=S.data.tasks.find(t=>t.id===form.dataset.id);Object.assign(t,task);reconcilePlan(t);}else S.data.tasks.unshift({...task,id:crypto.randomUUID(),done:false});save();closeModal();render();toast(task.scheduledAt?'任务与日历安排已同步保存':'任务已保存到个人空间');}
    if(form.id==='agent-model-form'){if(!requiredText(form,'model')||!requiredText(form,'profile')||!validUrl(form,'endpoint'))return;Object.assign(S.data.agent,d,{context:Number(d.context)});save();render();toast('模型配置已保存；未连接服务端，未验证模型可用性');}
    if(form.id==='agent-memory-form'){S.data.agent.persona=d.persona;S.data.agent.memory=d.memory;save();toast('助理设定和记忆已保存在本地');}
    if(form.id==='voice-settings-form'){S.data.agent.voice={voice:d.voice,rate:Number(d.rate),continuous:!!d.continuous};save();toast('语音偏好已保存');}
    if(form.id==='schedule-form'){if(!requiredText(form,'name')||!requiredText(form,'prompt'))return;S.data.agent.schedules.push({...d,id:crypto.randomUUID(),enabled:true});save();closeModal();render();toast('规则已保存，尚未启用后台调度');}
    if(form.id==='login-form'){if(!requiredText(form,'name'))return;S.data.user={...d,name:d.name.trim(),signedIn:true};save();closeModal();render();toast('演示身份已更新；不代表真实登录或云同步');}
    if(form.id==='add-module-form'){if(!requiredText(form,'name')||!validUrl(form,'endpoint'))return;if(S.data.modules.some(m=>m.name===d.name.trim())){toast('已经有同名能力');return;}S.data.modules.push({...d,name:d.name.trim(),desc:d.desc.trim()||'我的自定义能力',id:crypto.randomUUID(),installed:true,status:'待配置',color:'blue'});save();closeModal();navigate('modules');toast('自定义能力已添加到工作台');}
    if(form.id==='module-config-form'){if(!validUrl(form,'endpoint'))return;const m=S.data.modules.find(m=>m.id===form.dataset.id);m.endpoint=d.endpoint.trim();m.status='待连接';save();closeModal();render();toast('服务地址已保存，未建立真实连接');}
    if(form.id==='device-form'){if(!requiredText(form,'name'))return;S.data.devices.push({id:crypto.randomUUID(),name:d.name.trim()});save();closeModal();navigate('account');toast('已添加演示设备记录');}
    if(form.id==='event-form'){if(!requiredText(form,'title'))return;S.data.calendar.push({...d,title:d.title.trim(),id:crypto.randomUUID()});save();closeModal();navigate('calendar');toast('日程已保存到本地');}
    if(form.id==='plan-form'){if(d.end<=d.start){form.elements.end.setCustomValidity('结束时间必须晚于开始时间');form.elements.end.reportValidity();return;}if((d.start<'14:45'&&d.end>'14:00')||(d.start<'19:00'&&d.end>'18:30')){toast('这个时间与已有日程重叠，请选择其他时间');return;}S.data.planStart=d.start;S.data.planEnd=d.end;save();closeModal();render();toast('时间建议已更新，等待确认');}
    if(form.id==='chat-form'){if(!requiredText(form,'message'))return;ui.chat.push({role:'user',text:d.message.trim()});const text=/任务|待办|今天/.test(d.message)?`还有 ${S.data.tasks.filter(t=>!t.done).length} 项未完成任务。你可以从高优先级任务开始，或者确认上方的专注时间。这是本地预览回复。`:/代码|bug|修复/i.test(d.message)?'可以先打开 Hermes App，查看示例代码和待审阅变更。当前未连接真实仓库或执行环境，不会自动运行命令。':'当前处于交互预览，尚未连接 Hermes Agent。这条消息不会发送到模型或执行外部操作。';ui.chat.push({role:'assistant',text});render();$('.chat-log')?.scrollTo(0,99999);}
  });
  document.addEventListener('keydown',event=>{
    if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();search();}
    if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'&&ui.page==='workspace'){event.preventDefault();saveWorkspace();}
    if(event.key==='Escape'){if($('.modal'))closeModal();else{ui.menu=false;ui.aiDrawer=false;render();}}
    if(event.key==='Tab'&&$('.modal')){const focusables=$$('button,input,textarea,select,a[href]',$('.modal')).filter(e=>!e.disabled&&e.offsetParent!==null);if(event.shiftKey&&document.activeElement===focusables[0]){event.preventDefault();focusables.at(-1).focus();}else if(!event.shiftKey&&document.activeElement===focusables.at(-1)){event.preventDefault();focusables[0].focus();}}
  });
  window.addEventListener('storage',event=>{if(event.key!==S.key)return;S.reload();HermesFeatures.ensure();if(!ui.codeDirty)ui.codeDraft=S.data.code;if(!ui.noteDirty)ui.noteDraft=S.data.note;render();toast(ui.codeDirty||ui.noteDirty?'另一窗口有更新；你的未保存草稿仍保留':'已接收另一窗口的本地更新');});
  HermesVoice.bind(text=>{ui.chat.push({role:'user',text},{role:'assistant',text:'语音已转为文字。当前为本地预览，未连接 Hermes Agent。'});const transcript=$('#voice-transcript');if(transcript)transcript.textContent=text;render();},status=>{const label=$('#voice-status');if(label)label.textContent=status;$('#voice-symbol')?.classList.toggle('listening',HermesVoice.active);});
  window.speechSynthesis?.addEventListener('voiceschanged',()=>{const select=$('#voice-choice');if(select)select.innerHTML=HermesFeatures.voiceOptions();});
  window.addEventListener('pagehide',()=>HermesVoice.stop());
  window.addEventListener('beforeunload',event=>{if(ui.codeDirty||ui.noteDirty){event.preventDefault();event.returnValue='';}});
  render();
})();
