const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const fs=require('node:fs');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
  const page=await context.newPage();
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
  await page.evaluate(()=>localStorage.removeItem('hermes-terminal-v2'));
  await page.reload();
  await page.waitForFunction(()=>document.querySelectorAll('svg').length>30);
  const screenshots=path.resolve(__dirname,'../screenshots');
  fs.mkdirSync(screenshots,{recursive:true});
  const shot=async(name)=>page.screenshot({path:path.join(screenshots,`${name}.png`),fullPage:true,animations:'disabled'});
  const nav=async(name)=>page.locator(`.sidebar button[data-page="${name}"]`).click();
  await shot('v2-desktop');
  assert(await page.locator('.avatar').first().evaluate(e=>e.complete&&e.naturalWidth>0));
  await page.locator('.page-header [data-action="new-task"]').click();
  await page.getByLabel('任务名称',{exact:true}).fill('验证多窗口任务');
  await page.getByRole('button',{name:'创建任务',exact:true}).click();
  await page.reload();
  assert.equal(await page.getByRole('button',{name:'验证多窗口任务',exact:true}).count(),1);
  await page.getByRole('button',{name:'完成：验证多窗口任务',exact:true}).click();
  await nav('tasks');
  await page.locator('[data-task-filter="done"]').click();
  assert.equal(await page.getByRole('button',{name:'验证多窗口任务',exact:true}).count(),1);
  await nav('home');
  await page.locator('[data-action="adjust-plan"]').click();
  await page.getByLabel('开始时间',{exact:true}).fill('16:00');
  await page.getByLabel('结束时间',{exact:true}).fill('17:00');
  await page.getByRole('button',{name:'更新建议',exact:true}).click();
  assert.match(await page.locator('.ai-plan').innerText(),/16:00 – 17:00/);
  await page.locator('[data-action="approve-plan"]').click();
  await page.reload();
  assert.equal(await page.evaluate(()=>HermesStore.data.tasks.filter(e=>e.scheduledAt==='2026-09-18T16:00').length),1);
  await page.locator('[data-action="undo-plan"]').click();
  await nav('modules');
  await page.locator('[data-action="add-module"]').click();
  await page.getByLabel('名称',{exact:true}).fill('我的测试 MCP');
  await page.getByLabel('服务地址（可选）').fill('https://example.com/mcp');
  await page.getByRole('button',{name:'添加到工作台',exact:true}).click();
  await page.getByLabel('搜索能力').fill('我的测试');
  assert.equal(await page.locator('.module-card').count(),1);
  await page.getByLabel('搜索能力').fill('');
  await shot('v2-modules');
  await nav('workspace');
  await page.getByLabel('切换分屏',{exact:true}).click();
  const note=page.getByLabel('文档编辑器',{exact:true});
  await note.fill('# 测试文档\n\n跨窗口接续');
  await page.getByLabel('保存工作空间',{exact:true}).click();
  await page.getByLabel('查看变更',{exact:true}).click();
  await shot('v2-workspace');
  await page.getByRole('button',{name:'应用到本地示例',exact:true}).click();
  assert.match(await page.getByLabel('代码编辑器',{exact:true}).inputValue(),/response.status === 401/);
  await page.getByLabel('模拟运行检查',{exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.terminal-log').textContent.includes('No real compiler'));
  const popupPromise=page.waitForEvent('popup');
  await page.locator('[data-action="new-window"]').click();
  const popup=await popupPromise;
  await popup.waitForLoadState();
  assert.match(await popup.locator('h1').innerText(),/工作空间/);
  await popup.locator('[data-workspace="note"]').first().click();
  assert.match(await popup.getByLabel('文档编辑器',{exact:true}).inputValue(),/跨窗口接续/);
  await popup.getByLabel('文档编辑器',{exact:true}).fill('# 来自第二个窗口');
  await popup.getByLabel('保存工作空间',{exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#note-editor')?.value.includes('来自第二个窗口'));
  await popup.close();
  await nav('account');
  await page.locator('[data-action="pair-device"]').click();
  await page.getByLabel('设备名称',{exact:true}).fill('测试手机');
  await page.getByRole('button',{name:'模拟添加设备',exact:true}).click();
  assert.match(await page.locator('main').innerText(),/测试手机/);
  await shot('v2-account');
  await page.locator('.account-banner [data-action="login"]').click();
  await page.getByLabel('演示昵称',{exact:true}).fill('Taylor');
  await page.getByRole('button',{name:'进入演示工作空间',exact:true}).click();
  assert.match(await page.locator('.account-banner').innerText(),/Taylor/);
  await nav('calendar');
  await page.locator('.page-header [data-action="new-task"]').click();
  await page.getByLabel('任务名称',{exact:true}).fill('任务日历双向同步验证');
  await page.getByLabel('开始时间',{exact:true}).fill('10:00');
  await page.getByRole('button',{name:'创建任务',exact:true}).click();
  assert.equal(await page.locator('.agenda-copy').filter({hasText:'任务日历双向同步验证'}).count(),1);
  await page.getByRole('button',{name:'完成：任务日历双向同步验证',exact:true}).click();
  assert.equal(await page.locator('.agenda-row.done').count(),1);
  await nav('tasks');
  await page.locator('[data-task-filter="done"]').click();
  assert.equal(await page.getByRole('button',{name:'任务日历双向同步验证',exact:true}).count(),1);
  await page.getByRole('button',{name:'任务日历双向同步验证',exact:true}).click();
  await page.getByLabel('开始时间',{exact:true}).fill('10:45');
  await page.getByRole('button',{name:'保存修改',exact:true}).click();
  await nav('calendar');
  assert.match(await page.locator('.agenda-row.done').innerText(),/10:45/);
  await shot('v2-calendar');
  await page.getByRole('button',{name:'取消安排 任务日历双向同步验证',exact:true}).click();
  assert.equal(await page.locator('.agenda-row.done').count(),0);
  assert.equal(await page.evaluate(()=>HermesStore.data.tasks.filter(t=>t.title==='任务日历双向同步验证').length),1);
  await nav('agent');
  await page.getByLabel('默认模型 ID',{exact:true}).fill('gpt-4.1');
  await page.getByRole('button',{name:'保存模型配置',exact:true}).click();
  assert.match(await page.getByRole('button',{name:'选择 Hermes 模型',exact:true}).innerText(),/gpt-4.1/);
  await shot('v2-agent');
  await page.locator('[data-agent-tab="schedules"]').click();
  await page.locator('[data-action="new-schedule"]').click();
  await page.getByLabel('规则名称',{exact:true}).fill('测试周回顾');
  await page.getByLabel('交给 Hermes 的任务',{exact:true}).fill('整理已完成任务');
  await page.getByRole('button',{name:'保存规则',exact:true}).click();
  assert.match(await page.locator('.agent-settings').innerText(),/测试周回顾/);
  await page.locator('[data-agent-tab="voice"]').click();
  await page.getByRole('checkbox',{name:'连续对话',exact:true}).check();
  await page.getByRole('button',{name:'保存语音设置',exact:true}).click();
  assert.equal(await page.evaluate(()=>HermesStore.data.agent.voice.continuous),true);
  await page.locator('.page-header [data-action="voice"]').click();
  assert.equal(await page.locator('#voice-status').count(),1);
  await shot('v2-voice');
  await page.keyboard.press('Escape');
  for(const name of ['home','workspace','tasks','calendar','agent','runs','health','modules','connections','account']){
    await nav(name);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${name}: desktop overflow`);
  }
  await page.evaluate(()=>localStorage.removeItem('hermes-terminal-v2'));
  await page.reload();
  await page.setViewportSize({width:390,height:844});
  await shot('v2-mobile');
  for(const name of ['home','workspace','tasks','modules']){
    await page.locator(`.mobile-nav [data-page="${name}"]`).click();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${name}: mobile overflow`);
  }
  await page.locator('.mobile-nav [data-action="toggle-ai"]').click();
  assert(await page.locator('.assistant.drawer').isVisible());
  await page.getByLabel('发送给 Hermes 的消息',{exact:true}).fill('今天有哪些任务');
  await page.getByRole('button',{name:'发送',exact:true}).click();
  assert.equal(await page.locator('.assistant-message').count(),1);
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:360,height:800});
  await page.locator('.mobile-nav [data-page="home"]').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'360px overflow');
  assert.deepEqual(errors,[]);
  console.log('PASS: shared task/calendar completion and rescheduling, model selection, local schedules, voice UI, task persistence, plan approval, custom modules, workspace editing, diff approval, real popup and cross-window updates, demo account/devices, responsive navigation. No JS errors or horizontal overflow. Microphone hardware and online recognition were not tested.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
