const { chromium } = require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');

(async () => {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const url = pathToFileURL(path.join(__dirname, 'classic.html')).href;
  await page.goto(url);
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.waitForFunction(() => document.querySelectorAll('svg').length > 20);
  fs.mkdirSync(path.join(__dirname, 'screenshots'), { recursive: true });
  await page.screenshot({ path: path.join(__dirname, 'screenshots/desktop.png'), fullPage: true, animations: 'disabled' });
  assert.equal(await page.locator('.sidebar svg').count() > 10, true);
  assert.equal(await page.locator('.avatar').first().evaluate(img => img.complete && img.naturalWidth > 0), true);
  await page.locator('[data-action="new-task"]').first().click();
  await page.getByLabel('任务名称', { exact: true }).fill('验证：可持久化的工作台任务');
  await page.getByRole('button', { name: '创建任务', exact: true }).click();
  await page.reload();
  assert.equal(await page.getByRole('button', { name: '验证：可持久化的工作台任务', exact: true }).count(), 1);
  await page.getByRole('button', { name: '完成：验证：可持久化的工作台任务', exact: true }).click();
  await page.locator('[data-action="show-completed"]').click();
  assert.equal(await page.getByRole('button', { name: '验证：可持久化的工作台任务', exact: true }).count(), 1);
  await page.locator('[data-page="today"]').first().click();
  await page.locator('[data-action="approve-plan"]').click();
  await page.reload();
  assert.equal(await page.locator('[data-event="planned"]').count(), 1);
  await page.locator('[data-action="undo-plan"]').click();
  assert.equal(await page.locator('[data-event="planned"]').count(), 0);
  await page.getByRole('button', { name: '搜索', exact: true }).click();
  await page.getByLabel('搜索任务、项目、笔记').fill('验证：');
  assert.equal(await page.locator('.search-result').count(), 1);
  await page.keyboard.press('Escape');
  for (const name of ['calendar', 'health', 'projects', 'notes', 'inbox', 'tasks']) {
    await page.locator(`.sidebar [data-page="${name}"]`).click();
    assert.equal(await page.locator('main h1').count(), 1);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `${name} desktop overflow`);
  }
  await page.locator('.sidebar [data-page="notes"]').click();
  await page.locator('[data-action="new-note"]').click();
  await page.getByLabel('标题', { exact: true }).fill('验证笔记');
  await page.getByLabel('内容', { exact: true }).fill('笔记内容应在刷新之后保留。');
  await page.getByRole('button', { name: '保存笔记', exact: true }).click();
  await page.reload();
  await page.locator('.sidebar [data-page="notes"]').click();
  await page.getByRole('button', { name: /验证笔记/ }).click();
  assert.equal(await page.getByLabel('内容', { exact: true }).inputValue(), '笔记内容应在刷新之后保留。');
  await page.keyboard.press('Escape');
  await page.locator('.sidebar [data-page="calendar"]').click();
  await page.locator('.week-grid [data-event="focus"]').first().click();
  assert.match(await page.locator('.detail-meta').innerText(), /15.*星期二/);
  await page.keyboard.press('Escape');
  await page.locator('.sidebar [data-page="health"]').click();
  await page.locator('[data-health-tab="steps"]').click();
  assert.equal(await page.locator('.chart-bar').count(), 7);
  await page.screenshot({ path: path.join(__dirname, 'screenshots/health.png'), fullPage: true, animations: 'disabled' });
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(__dirname, 'screenshots/mobile.png'), fullPage: true, animations: 'disabled' });
  assert.equal(await page.locator('.sidebar').evaluate(e => e.getBoundingClientRect().right <= 0), true, 'mobile sidebar is offscreen');
  for (const name of ['today', 'calendar', 'tasks', 'health']) {
    await page.locator(`.mobile-bottom [data-page="${name}"]`).click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `${name} mobile overflow`);
  }
  await page.locator('.mobile-bottom [data-action="assistant"]').click();
  assert.equal(await page.locator('.assistant.open').isVisible(), true);
  await page.locator('.assistant [name="message"]').fill('今天的待办');
  await page.locator('.send-button').click();
  assert.equal(await page.locator('.chat-reply').count(), 1);
  await page.keyboard.press('Escape');
  await page.locator('.mobile-bottom [data-page="today"]').click();
  await page.locator('[data-action="new-task"]').first().click();
  await page.screenshot({ path: path.join(__dirname, 'screenshots/mobile-dialog.png'), fullPage: true, animations: 'disabled' });
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 360, height: 800 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, '360px overflow');
  assert.deepEqual(errors, []);
  console.log('PASS: desktop/mobile navigation, task/note persistence, task completion, plan approval/undo, search, correct calendar dates, charts, local chat, images/icons, no JS errors or horizontal overflow.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
