const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const { mkdtempSync, mkdirSync, rmSync } = require('node:fs');
const { join } = require('node:path');
const { tmpdir } = require('node:os');

(async () => {
  const { createApp } = await import('../app.mjs');
  const { testConfig, mockAuth, modelFixture, mockGateway } = await import('./fixtures.mjs');
  const dir = mkdtempSync(join(tmpdir(), 'hermes-browser-'));
  const config = testConfig(dir);
  const model=modelFixture();
  const app = await createApp(config, { auth: mockAuth, hermesTransport: model.transport, gateway: mockGateway });
  let browser;
  try {
    await app.listen({ host: '127.0.0.1', port: 0 });
    config.origin = `http://127.0.0.1:${app.server.address().port}`;
    browser = await chromium.launch({ headless: true });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage(), errors = [];
    const go = async id => {
      if (page.viewportSize().width <= 760) await page.getByRole('button', { name: '打开导航', exact: true }).click();
      await page.locator(`.sidebar .nav button[data-page="${id}"]`).click();
    };
    page.on('pageerror', e => errors.push(e.message));
    mkdirSync('test-results', { recursive: true });
    await page.goto(config.origin);
    await page.getByRole('button', { name: '忘记密码？' }).click();
    await page.getByText('应用账号暂未开通自助找回。请联系账号管理员，核验身份后重置密码。').waitFor();
    await page.getByRole('button', { name: '返回登录' }).click();
    await page.getByRole('button', { name: '创建账号', exact: true }).click();
    await page.locator('#register-form [name=name]').fill('Browser User');
    await page.locator('#register-form [name=username]').fill('browseruser');
    await page.getByLabel('联系 QQ').fill('12345678');
    await page.locator('#register-form [name=password]').fill('test-password');
    await page.getByLabel('确认密码').fill('mismatch');
    await page.locator('#register-form button[type=submit]').click();
    await page.getByText('两次输入的密码不一致。').waitFor();
    await page.getByLabel('确认密码').fill('test-password');
    await page.setViewportSize({ width: 360, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: 'test-results/register-mobile.png', fullPage: true });
    await page.locator('#register-form button[type=submit]').click();
    await page.locator('dialog').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('#login-form [name=username]').inputValue(), 'browseruser');
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('#login-form [name=username]').fill('browser-user');
    await page.locator('#login-form [name=password]').fill('test-password');
    await page.getByRole('button', { name: '登录', exact: true }).click();
    await page.getByRole('heading', { name: '你好，browser-user' }).waitFor();
    assert.equal(await page.locator('.body-layout > .assistant').count(), 1);
    assert.equal(await page.locator('.overview-project-empty').count(), 1);
    assert.equal(await page.locator('.summary-item').count(), 4);
    assert.equal(await page.locator('script[src*="terminal/store.js"]').count(), 0);
    await page.getByRole('button', { name: '新建任务' }).click();
    await page.getByLabel('任务名称', { exact: true }).fill('发布第一版工作台');
    const today = await page.evaluate(() => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; });
    await page.getByLabel('日历时间').fill(`${today}T14:00`);
    await page.getByRole('button', { name: '保存', exact: true }).click();
    await page.locator('dialog').waitFor({ state: 'hidden' });
    await page.getByRole('checkbox', { name: '完成任务：发布第一版工作台' }).waitFor();
    assert.equal(await page.locator('.event strong').innerText(), '发布第一版工作台');
    const second = await context.newPage(); await second.goto(config.origin);
    await second.getByRole('checkbox', { name: '完成任务：发布第一版工作台' }).waitFor();
    await page.getByRole('checkbox', { name: '完成任务：发布第一版工作台' }).check();
    await page.locator('.event.done').waitFor();
    await second.locator('.event.done').waitFor();
    await page.screenshot({ path: 'test-results/workbench-desktop.png', fullPage: true });
    await go('hermes');
    assert.equal(await page.getByRole('tablist', { name: 'Hermes 管理' }).getByRole('tab').count(), 6);
    await page.getByRole('tab', { name: '工具权限', exact: true }).click();
    await page.getByText('工作台上下文', { exact: true }).waitFor();
    await page.getByRole('tab', { name: '模型', exact: true }).click();
    await page.getByLabel('服务器地址').fill('https://hermes.example.test');
    await page.getByLabel('Hermes 用户名').fill('remote-user');
    await page.getByLabel('Hermes 密码').fill('hermes-test-password');
    await page.getByRole('button', { name: '连接服务器' }).click();
    await page.getByRole('button', { name: '获取模型' }).click();
    await page.getByLabel('搜索模型',{exact:true}).fill('model-b');
    page.once('dialog',dialog=>dialog.accept());
    await page.getByRole('button', { name: '应用到新会话' }).click();
    await page.getByText('default · 新会话默认模型：fixture-model-b',{exact:true}).waitFor();
    assert.equal(model.writes.length,1);assert.equal(model.writes[0].confirm_expensive_model,false);
    await page.getByRole('tab',{name:'工具权限',exact:true}).click();
    await page.locator('[data-context-task]').first().check();await page.locator('[data-agent-share]').click();
    await page.locator('[data-pending-preview]').filter({hasText:'workbench-tasks.json'}).click();
    assert.ok((await page.locator('.document-content code').innerText()).includes('发布第一版工作台'));
    await page.getByRole('button',{name:'关闭预览',exact:true}).click();await page.locator('[data-remove-file]').click();
    await page.getByRole('tab',{name:'模型',exact:true}).click();
    await page.screenshot({ path: 'test-results/hermes-desktop.png', fullPage: true });
    await page.getByLabel('发送给 Hermes 的消息').fill('approval');
      page.once('dialog', dialog => dialog.accept());
    await page.getByRole('button',{name:'发送',exact:true}).click();
    await page.getByRole('button',{name:'仅本次允许',exact:true}).waitFor();
    await page.screenshot({path:'test-results/chat-approval.png',fullPage:true});
    await page.getByRole('button',{name:'仅本次允许',exact:true}).click();
    await page.locator('.chat-output').filter({hasText:'真实协议测试回复'}).waitFor();
    await page.locator('.live-run-status').filter({hasText:'已完成'}).waitFor();
    await page.screenshot({path:'test-results/chat-completed.png',fullPage:true});
    await page.getByRole('button',{name:'保存为工作空间文档',exact:true}).click();
    await page.getByLabel('文档内容',{exact:true}).waitFor();
    assert.equal(await page.getByLabel('文档内容',{exact:true}).inputValue(),'真实协议测试回复');
    let repeatedConsent=0;
    page.on('dialog', async dialog => { repeatedConsent++; await dialog.dismiss(); });
    const documentText='# 项目说明\n\n**真实附件**\n\n<script>window.previewAttack=1</script>\n<img src=x onerror="window.previewAttack=1">\n[危险链接](javascript:alert(1))';
    await page.locator('#chat-file-input').setInputFiles({name:'项目说明.md',mimeType:'text/markdown',buffer:Buffer.from(documentText)});
    await page.locator('[data-pending-preview]').click();
    await page.locator('#document-preview h1').filter({hasText:'项目说明'}).waitFor();
    assert.equal(await page.locator('#document-preview script,#document-preview img,#document-preview a[href^="javascript:"]').count(),0);
    assert.equal(await page.evaluate(()=>window.previewAttack),undefined);
    await page.locator('[data-preview-mode=source]').click();
    assert.equal(await page.locator('.document-content code').innerText(),documentText);
    await page.getByRole('button',{name:'关闭预览',exact:true}).click();
    await page.getByLabel('发送给 Hermes 的消息').fill('请阅读附件。\n'+('这是一段长消息，用于验证对话滚动。\n'.repeat(50)));
    await page.getByRole('button',{name:'发送',exact:true}).click();
    await page.waitForFunction(()=>document.querySelectorAll('.chat-turn').length===2&&document.querySelector('.live-run-status').textContent==='已完成');
    assert.equal(repeatedConsent,0);
    await page.locator('.chat-context summary').click();
    assert.equal(await page.locator('.chat-turn').count(),2);
    assert.equal(await page.locator('.live-chat-log').evaluate(el=>el.scrollHeight>el.clientHeight),true);
    await page.locator('.live-chat-log').evaluate(el=>el.scrollTop=0);
    await page.getByRole('button',{name:'展开对话',exact:true}).click();
    assert.equal(await page.locator('.live-chat-log').evaluate(el=>el.scrollTop),0);
    await page.locator('[data-file-run]').click();
    await page.locator('#document-preview h1').waitFor();
    await page.screenshot({path:'test-results/document-preview.png',fullPage:true});
    await page.getByRole('button',{name:'关闭预览',exact:true}).click();
    await page.reload();
    await page.locator('[data-file-run]').waitFor();
    assert.equal(await page.locator('.chat-turn').count(),2);
    await page.getByRole('button',{name:'展开对话',exact:true}).click();
    await page.screenshot({path:'test-results/chat-workspace.png',fullPage:true});
    for (const width of [390, 360]) {
      await page.setViewportSize({ width, height: 844 });
      for (const name of ['home', 'workspace', 'tasks', 'calendar', 'hermes', 'runs', 'health', 'modules', 'connections', 'account']) {
        await go(name);
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `${name} overflow at ${width}`);
      }
      await go('home');
      await page.screenshot({ path: `test-results/workbench-mobile-${width}.png`, fullPage: true });
      await page.getByRole('button', { name: '切换 Hermes 面板', exact: true }).click();
      await page.locator('.assistant.drawer').waitFor({ state: 'visible' });
      assert.equal(await page.getByLabel('发送给 Hermes 的消息').isDisabled(), false);
      assert.equal(await page.locator('.live-chat-log').evaluate(el=>el.scrollHeight>el.clientHeight),true);
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
      const composer=await page.locator('#live-chat-form').boundingBox();
      assert.ok(composer.y+composer.height<=844-64+1,'composer above bottom navigation');
      await page.screenshot({path:`test-results/chat-mobile-${width}.png`,fullPage:true});
      await page.getByRole('button', { name: '收起助手', exact: true }).click();
    }
    await go('account');
    await page.getByRole('button', { name: '退出登录', exact: true }).last().click();
    await page.getByRole('heading', { name: '回到你的工作与生活' }).waitFor();
    await page.screenshot({ path: 'test-results/login-mobile.png', fullPage: true });
    assert.deepEqual(errors, []);
    console.log('PASS: registration, recovery boundary, login, task/calendar, cross-window sync, Hermes models, mobile 390/360, logout; no JS errors');
  } finally {
    await browser?.close(); await app.close(); rmSync(dir, { recursive: true, force: true });
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
