const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),{mkdtempSync,rmSync,mkdirSync}=require('node:fs'),{join}=require('node:path'),{tmpdir}=require('node:os'),{randomUUID}=require('node:crypto');
(async()=>{
 const {createApp}=await import('../app.mjs'),{testConfig,mockAuth,mockHermes,mockGateway}=await import('./fixtures.mjs');const dir=mkdtempSync(join(tmpdir(),'hermes-calendar-')),config=testConfig(dir),app=await createApp(config,{auth:mockAuth,gateway:mockGateway,hermesTransport:async(url,o)=>new URL(url).pathname==='/api/tools/toolsets'?{status:200,headers:{},text:JSON.stringify({toolsets:[{name:'delegation',enabled:true,tools:['delegate_task']}]})}:mockHermes(url,o)});let browser;
 try{
  await app.listen({host:'127.0.0.1',port:0});config.origin=`http://127.0.0.1:${app.server.address().port}`;browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:960}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  const login=await context.request.post(config.origin+'/api/auth/login',{headers:{origin:config.origin},data:{username:'calendar-user',password:'test-password'}}),session=await login.json(),headers={origin:config.origin,'x-csrf-token':session.csrf};
  await context.request.post(config.origin+'/api/hermes/connect',{headers,data:{origin:'https://hermes.example.test',username:'remote-user',password:'hermes-test-password'}});
  const taskId=randomUUID();await context.request.post(config.origin+'/api/tasks',{headers:{...headers,'idempotency-key':randomUUID()},data:{id:taskId,version:0,title:'Design review',scheduledAt:'2026-09-18T09:00:00.000Z',minutes:30,timeZone:'UTC',completed:false,deleted:false}});
  await page.goto(config.origin);await page.locator('.sidebar [data-page=calendar]').click();await page.locator('#calendar-date').fill('2026-09-18');await page.locator('#calendar-date').dispatchEvent('change');assert.equal(await page.locator('.calendar-cell').count(),42);await page.locator(`.calendar-task[data-edit="${taskId}"]`).click();assert.equal(await page.locator('#task-form input[name=title]').inputValue(),'Design review');await page.locator('#editor [data-action=close]').first().click();
  await page.locator('[data-calendar-view=week]').click();assert.equal(await page.locator('.calendar-cell').count(),7);await page.locator('[data-day="1"]').click();assert.equal(await page.locator('#calendar-date').inputValue(),'2026-09-25');await page.locator('[data-calendar-view=month]').click();await page.locator('#calendar-date').fill('2026-12-31');await page.locator('#calendar-date').dispatchEvent('change');await page.locator('[data-day="1"]').click();assert.equal(await page.locator('#calendar-date').inputValue(),'2027-01-01');
  mkdirSync('test-results',{recursive:true});await page.locator('#calendar-date').fill('2026-09-18');await page.locator('#calendar-date').dispatchEvent('change');await page.waitForTimeout(300);await page.screenshot({path:'test-results/calendar-month-desktop.png'});
  for(const width of [390,360]){await page.setViewportSize({width,height:844});await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:`test-results/calendar-month-${width}.png`});}
  await page.setViewportSize({width:1440,height:960});await page.getByRole('button',{name:'展开对话',exact:true}).click();await page.locator('.chat-context>summary').click();await page.getByRole('button',{name:'Agent 协作',exact:true}).click();await page.locator('[data-chat-action=agent-mode][aria-pressed=true]').waitFor();await page.locator('.chat-context>summary').click();await page.getByLabel('发送给 Hermes 的消息').fill('Plan a review');await page.getByRole('button',{name:'发送',exact:true}).click();await page.locator('.live-run-status').filter({hasText:'已完成'}).waitFor();
  await page.getByRole('button',{name:'历史会话',exact:true}).click();await page.locator('[data-session-edit]').first().click();await page.getByLabel('会话名称',{exact:true}).fill('Weekly review');await page.locator('#session-editor input[name=category]').fill('Work');await page.locator('#session-editor [type=submit]').click();await page.locator('#session-editor').waitFor({state:'detached'});await page.locator('#session-category-filter').selectOption('Work');assert.match(await page.locator('.session-entry').innerText(),/Weekly review/);
  await page.reload();await page.getByRole('button',{name:'历史会话',exact:true}).click();assert.match(await page.locator('.session-entry').innerText(),/Weekly review/);await page.setViewportSize({width:390,height:844});await page.locator('.mobile-nav [data-action=toggle-ai]').click();if(!await page.locator('.chat-session-drawer').isVisible())await page.getByRole('button',{name:'历史会话',exact:true}).click();await page.waitForTimeout(300);await page.screenshot({path:'test-results/conversation-history-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS calendar periods, shared task editor, responsive month, agent preference, rename/category persistence');
 }finally{await browser?.close();await app.close();rmSync(dir,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
