const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),{mkdtempSync,rmSync}=require('node:fs'),{join}=require('node:path'),{tmpdir}=require('node:os');
(async()=>{
 const {createApp}=await import('../app.mjs'),{testConfig,mockAuth,mockHermes,mockGateway}=await import('./fixtures.mjs');const dir=mkdtempSync(join(tmpdir(),'hermes-drop-')),config=testConfig(dir),app=await createApp(config,{auth:mockAuth,hermesTransport:mockHermes,gateway:mockGateway});let browser;
 try{
  await app.listen({host:'127.0.0.1',port:0});config.origin=`http://127.0.0.1:${app.server.address().port}`;browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:960}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  const login=await context.request.post(config.origin+'/api/auth/login',{headers:{origin:config.origin},data:{username:'drop-user',password:'test-password'}}),session=await login.json();await context.request.post(config.origin+'/api/hermes/connect',{headers:{origin:config.origin,'x-csrf-token':session.csrf},data:{origin:'https://hermes.example.test',username:'remote-user',password:'hermes-test-password'}});
  await page.goto(config.origin);await page.locator('.assistant').waitFor();
  const transfer=await page.evaluateHandle(()=>{const d=new DataTransfer();d.items.add(new File(['# Release\n\nReview notes'],'release.md',{type:'text/markdown'}));return d;});
  await page.locator('.assistant').dispatchEvent('dragover',{dataTransfer:transfer});await page.locator('#chat-drop-hint').waitFor();await page.locator('.assistant').dispatchEvent('drop',{dataTransfer:transfer});await page.locator('[data-pending-preview]').waitFor();assert.equal(await page.locator('#chat-drop-hint').count(),0);await page.locator('[data-pending-preview]').click();assert.equal(await page.locator('.document-content h1').innerText(),'Release');await page.getByRole('button',{name:'关闭预览',exact:true}).click();
  const png=await page.evaluateHandle(()=>{const d=new DataTransfer();d.items.add(new File(['image'],'photo.png',{type:'image/png'}));return d;});await page.locator('.assistant').dispatchEvent('drop',{dataTransfer:png});await page.locator('#notice').filter({hasText:'暂不支持图片'}).waitFor();assert.equal(await page.locator('[data-pending-preview]').count(),1);
  await page.locator('[data-remove-file]').click();await page.getByLabel('发送给 Hermes 的消息').fill('hold');await page.getByRole('button',{name:'发送',exact:true}).click();await page.locator('.live-run-status').filter({hasText:'正在执行'}).waitFor();await page.locator('.assistant').dispatchEvent('drop',{dataTransfer:transfer});await page.locator('#notice').filter({hasText:'请先结束或核对当前执行，再添加附件。'}).waitFor();assert.equal(await page.locator('[data-pending-preview]').count(),0);await page.getByRole('button',{name:'中断执行',exact:true}).click();await page.locator('.live-run-status').filter({hasText:'已中断'}).waitFor();
  const prevented=await page.locator('#main').evaluate((el,d)=>!el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:d})),transfer);assert.equal(prevented,true);assert.equal(page.url(),config.origin+'/');assert.deepEqual(errors,[]);console.log('PASS: drop highlight, real text attachment/preview, unsupported image feedback, active-run feedback and navigation prevention');
 }finally{await browser?.close();await app.close();rmSync(dir,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
