const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),{mkdtempSync,rmSync,mkdirSync}=require('node:fs'),{join}=require('node:path'),{tmpdir}=require('node:os');
(async()=>{
 const {createApp}=await import('../app.mjs'),{testConfig,mockAuth,mockGateway}=await import('./fixtures.mjs'),{profileFixture}=await import('./profile-fixture.mjs');const dir=mkdtempSync(join(tmpdir(),'hermes-simple-')),config=testConfig(dir),f=profileFixture(),app=await createApp(config,{auth:mockAuth,hermesTransport:f.transport,gateway:mockGateway});let browser;
 try{
  await app.listen({host:'127.0.0.1',port:0});config.origin=`http://127.0.0.1:${app.server.address().port}`;browser=await chromium.launch({headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:960}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  const login=await ctx.request.post(config.origin+'/api/auth/login',{headers:{origin:config.origin},data:{username:'simple-user',password:'test-password'}}),session=await login.json();await ctx.request.post(config.origin+'/api/hermes/connect',{headers:{origin:config.origin,'x-csrf-token':session.csrf},data:{origin:'https://hermes.example.test',username:'remote-user',password:'hermes-test-password'}});
  await page.goto(config.origin);await page.locator('.sidebar [data-page=hermes]').click();assert.equal(await page.locator('[data-agent-tab=profiles],[data-choose-agent],[data-profiles-create]').count(),0);await page.locator('[data-agent-tab=collaboration]').click();await page.locator('[data-collaboration-field=children]').fill('4');await page.locator('#hermes-collaboration-form [type=submit]').click();await page.waitForFunction(()=>document.querySelector('[data-collaboration-dirty]')?.textContent.includes('与服务器一致'));assert.deepEqual(f.writes.at(-1).body,{config:{delegation:{max_concurrent_children:4}}});await page.locator('[data-collaboration-refresh]').click();await page.waitForFunction(()=>document.querySelector('[data-collaboration-field=children]')?.value==='4'&&!document.querySelector('[data-collaboration-refresh]')?.disabled);
  await page.locator('[data-collaboration-enabled]').click();await page.waitForFunction(()=>document.querySelector('[data-collaboration-enabled]')?.checked===false&&!document.querySelector('[data-collaboration-enabled]')?.disabled);assert.equal(f.profiles.get('default').enabled,false);
  mkdirSync('test-results',{recursive:true});for(const width of [1440,390,360]){await page.setViewportSize({width,height:900});await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:`test-results/hermes-simple-${width}.png`});}
  await page.locator('.mobile-nav [data-action=toggle-ai]').click();assert.equal(await page.locator('.compose-footer [data-chat-action=agent-mode],.compose-footer [data-choose-agent]').count(),0);await page.waitForTimeout(300);await page.screenshot({path:'test-results/hermes-simple-chat.png'});assert.deepEqual(errors,[]);console.log('PASS Hermes-only navigation, no Agent creation/selector, verified delegation settings, compact composer, mobile layouts');
 }finally{await browser?.close();await app.close();rmSync(dir,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
