'use strict';
window.HermesExternalAgents=(()=>{
 let context,data=null,busy=false,error='',epoch=0;
 const e=v=>window.HermesViews.esc(v),i=n=>window.HermesViews.icon(n);
 function reset(){epoch++;data=null;busy=false;error='';}
 async function refresh(){if(busy)return;const version=epoch;busy=true;error='';context.render();try{const result=await context.api('/hermes/external-agents');if(version===epoch)data=result;}catch(cause){if(version===epoch){data=null;error=cause.message;}}finally{if(version===epoch){busy=false;context.render();}}}
 function panel(){return `<section class="external-agents"><div class="section-head"><h2>外部 Agent</h2><button class="secondary" data-external-agents-refresh ${busy?'disabled':''}>${i('refresh-cw')}检查服务器</button></div><p class="inline-status">${e(context.state.hermes.origin||'未连接 Hermes')}</p>${error?`<p class="form-error" role="alert">${e(error)}</p>`:''}${data?`<div class="external-agent-readiness"><span>${i('server')}Hermes 执行环境</span><strong>${e(data.terminal.backend||'未知')}</strong><span class="tag">${data.terminal.status==='ready'?'终端就绪':data.terminal.status==='needs_setup'?'终端待配置':data.terminal.status==='unavailable'?'终端不可用':'终端状态未确认'}</span></div><p class="external-agent-warning" role="status">当前服务器未接入外部 CLI 管理，无法核验安装、版本或登录状态。</p><div class="external-agent-grid">${data.items.map(a=>`<article class="external-agent-card"><header><span class="external-agent-symbol">${i('terminal')}</span><div><h3>${e(a.name)}</h3><small>${e(a.vendor)}</small></div><span class="tag">待核验</span></header><dl><div><dt>安装状态</dt><dd>未知</dd></div><div><dt>账号授权</dt><dd>未核验</dd></div><div><dt>Hermes 调用</dt><dd>未核验</dd></div></dl><footer><button class="secondary" data-external-agent-check="${a.id}" ${data.terminal.status!=='ready'?'disabled':''}>${i('message-square')}交给 Hermes 检查</button><button class="icon-button" data-external-agent-plan="${a.id}" title="准备接入方案" aria-label="准备 ${e(a.name)} 接入方案">${i('settings-2')}</button></footer></article>`).join('')}</div><p class="inline-status">${e(new Date(data.checkedAt).toLocaleString(I18n.locale))}</p>`:`<div class="empty-state">${busy?'正在检查服务器…':'尚未检查服务器'}</div>`}</section>`;}
 document.addEventListener('click',ev=>{const b=ev.target.closest('[data-external-agents-refresh],[data-external-agent-check],[data-external-agent-plan],[data-agent-tab=external]');if(!b||busy)return;if(b.hasAttribute('data-external-agents-refresh')||b.dataset.agentTab==='external'){if(!data||b.hasAttribute('data-external-agents-refresh'))void refresh();return;}const a=data?.items.find(a=>a.id===(b.dataset.externalAgentCheck||b.dataset.externalAgentPlan));if(!a)return;
  const text=b.dataset.externalAgentCheck?`请只读检查你的执行环境中的 ${a.name}。核对实际主机或容器、CLI 是否存在和版本。只有官方支持的只读状态接口才可用于检查授权；不要读取或输出密钥、令牌、账号文件或完整环境变量。不要安装、升级、登录、修改文件或调用模型。报告每一步的真实结果与未确认项。终端不可用时明确说明，不猜测。`:`请为在你的执行环境中接入 ${a.name} 准备方案。先只读核对主机或容器、现有安装和官方文档，列出安装来源、版本、权限、账号授权方式，以及你实际如何调用它并回收结果。只给方案，不执行安装、升级、删除、登录或模型推理；需要修改服务器时等待我明确确认。不要把模型提供商或图像插件当成编码 CLI。`;
  window.HermesChat.prepareExternalAgent(text);
 });
 return {configure:c=>context=c,reset,panel};
})();
