'use strict';
window.HermesProfiles=(()=>{
 const e=v=>window.HermesViews.esc(v),i=n=>window.HermesViews.icon(n);
 const fields={maxTurns:['执行轮数上限',1,500],timeout:['网关超时（秒）',0,7200],childTurns:['子任务轮数上限',1,250],children:['并发子任务上限',1,10],depth:['委派深度上限',1,3],childTimeout:['子任务超时（秒）',30,3600],orchestrator:['允许子任务继续分工']};
 let context,detail=null,draft={},busy=false,error='',blocked=false,epoch=0;
 const dirty=()=>Object.keys(draft).length>0;
 function reset(){window.HermesExternalAgents?.reset();epoch++;detail=null;draft={};busy=false;error='';blocked=false;}
 async function load(){if(busy)return;if(dirty()&&!confirm('重新读取将放弃未保存修改，继续？'))return;const version=epoch;busy=true;error='';context.render();try{const result=await context.api('/hermes/profiles/default');if(version!==epoch)return;detail=result;draft={};blocked=false;}catch(cause){if(version===epoch)error=cause.message;}finally{if(version===epoch){busy=false;context.render();}}}
 function panel(){const delegation=detail?.tools.find(t=>t.tools.includes('delegate_task'));return `<section class="agent-section"><div class="section-head"><h2>Hermes 协作</h2><button class="secondary" data-collaboration-refresh ${busy?'disabled':''}>${i('refresh-cw')}读取设置</button></div><p class="inline-status">共享服务器配置 · default</p><p class="form-error" role="alert">${e(error)}</p>${detail?`${delegation?`<label class="setting-row"><strong>允许 Hermes 分派子任务</strong><input type="checkbox" data-collaboration-enabled ${delegation.enabled?'checked':''} ${busy||blocked||delegation.enabled===null?'disabled':''}></label>`:''}<form id="hermes-collaboration-form">${Object.entries(detail.runtime).map(([key,value])=>{const v=Object.hasOwn(draft,key)?draft[key]:value,[label,min,max]=fields[key];return `<label class="setting-row"><strong>${e(label)}</strong><input data-collaboration-field="${key}" aria-label="${e(label)}" type="${typeof value==='boolean'?'checkbox':'number'}" ${typeof value==='boolean'?(v?'checked':''):`value="${v}" min="${min}" max="${max}" step="1" required`} ${busy?'disabled':''}></label>`;}).join('')}<div class="setting-actions"><button class="primary" type="submit" ${busy||blocked?'disabled':''}>${i('save')}保存设置</button><button class="secondary" type="button" data-collaboration-discard ${busy?'disabled':''}>放弃修改</button><span class="inline-status" data-collaboration-dirty>${dirty()?'有未保存修改':'与服务器一致'}</span></div></form>`:`<div class="empty-state">${busy?'正在读取设置…':'尚未读取服务器'}</div>`}</section>`;}
 async function save(body){if(busy||blocked)return;if(!confirm('修改 Hermes 共享协作设置？可能影响其他客户端和模型费用，已有会话可能需要新建才能生效。')){context.render();return;}const version=epoch;busy=true;error='';context.render();try{const result=await context.api('/hermes/profiles',{method:'POST',body:{...body,name:'default',revision:detail.revision,confirm:true}});if(version!==epoch)return;detail=result;draft={};context.notify('Hermes 协作设置已保存并核验');}catch(cause){if(version===epoch){error=cause.message;blocked=true;}}finally{if(version===epoch){busy=false;context.render();}}}
 document.addEventListener('click',ev=>{if(ev.target.closest('[data-collaboration-refresh]'))void load();if(ev.target.closest('[data-collaboration-discard]')&&!busy){draft={};context.render();}if(ev.target.closest('[data-agent-tab=collaboration]')&&!detail&&!busy)void load();});
 document.addEventListener('input',ev=>{const el=ev.target,key=el.dataset.collaborationField;if(!key||busy)return;draft[key]=el.type==='checkbox'?el.checked:Number(el.value);const status=document.querySelector('[data-collaboration-dirty]');if(status)status.textContent='有未保存修改';});
 document.addEventListener('change',ev=>{if(!ev.target.matches('[data-collaboration-enabled]'))return;const enabled=ev.target.checked;ev.target.checked=!enabled;if(dirty()){context.notify('请先保存执行参数，再切换协作权限。');return;}const tool=detail?.tools.find(t=>t.tools.includes('delegate_task'));if(tool)void save({action:'tool',tool:tool.id,enabled});});
 document.addEventListener('submit',ev=>{if(ev.target.id!=='hermes-collaboration-form')return;ev.preventDefault();const changes=Object.fromEntries(Object.entries(draft).filter(([key,value])=>value!==detail.runtime[key]));if(Object.keys(changes).length)void save({action:'runtime',changes});});
 window.addEventListener('beforeunload',ev=>{if(dirty()){ev.preventDefault();ev.returnValue='';}});
 return {configure:c=>context=c,reset,panel,dirty};
})();
