'use strict';
window.HermesProjects=(()=>{
  const e=v=>window.HermesViews.esc(v),i=n=>window.HermesViews.icon(n);
  let context,items=[],selected=null,epoch=0,sequence=0,busy=false,loaded=false,error='',query='',archived=false,draft=null,picker=null,docs=[],conflict=false;
  function configure(c){context=c;}
  function reset(){epoch++;sequence++;items=[];selected=null;busy=false;loaded=false;error='';query='';archived=false;draft=null;picker=null;docs=[];conflict=false;}
  async function load(){const version=epoch,seq=++sequence;const result=await context.api('/projects');if(version!==epoch||seq!==sequence)return;items=result.projects;loaded=true;if(!selected)selected=items.find(p=>!p.archived)?.id;}
  function conflictView(){const remote=draft&&items.find(p=>p.id===draft.id);if(!conflict||!remote)return '';return `<div class="project-conflict"><strong>服务器版本</strong><p>${e(remote.name)}</p><p>${e(remote.description)}</p><div class="project-actions"><button class="secondary" data-project-action="reload-draft">载入服务器版本</button><button class="secondary" data-project-action="rebase">保留我的文字修改</button></div></div>`;}
  const current=()=>items.find(p=>p.id===selected);
  const tasks=p=>context.state.tasks.filter(t=>p.taskIds.includes(t.id)&&!t.deleted);
  function tabs(){return `<div class="workspace-switch" role="tablist" aria-label="工作空间视图"><button role="tab" data-workspace-view="projects" aria-selected="${context.state.workspaceView!=='documents'}">${i('folder-kanban')}项目</button><button role="tab" data-workspace-view="documents" aria-selected="${context.state.workspaceView==='documents'}">${i('files')}全部文档</button></div>`;}
  function editor(){return `<section class="project-edit">${conflictView()}<h2>${draft.version?'编辑项目':'新建项目'}</h2><label>项目名称<input aria-label="项目名称" data-project-field="name" value="${e(draft.name)}" maxlength="100" ${busy?'disabled':''}></label><label>项目说明<textarea aria-label="项目说明" data-project-field="description" maxlength="2000" rows="4" ${busy?'disabled':''}>${e(draft.description)}</textarea></label><div class="project-actions"><button class="secondary" data-project-action="cancel" ${busy?'disabled':''}>取消</button><button class="primary" data-project-action="save" ${busy?'disabled':''}>${i('save')}保存项目</button></div></section>`;}
  function linkPicker(p){if(!picker)return '';const options=picker==='task'?context.state.tasks.filter(t=>!p.taskIds.includes(t.id)).map(t=>({id:t.id,name:t.title})):docs.filter(d=>!d.deleted&&!p.documents.some(v=>v.id===d.id));return `<div class="project-link-picker"><label>${picker==='task'?'关联已有任务':'关联已有文档'}<select id="project-resource" ${busy?'disabled':''}><option value="">选择内容</option>${options.map(v=>`<option value="${v.id}">${e(v.name)}</option>`).join('')}</select></label><button class="primary" data-project-action="link" ${busy?'disabled':''}>关联</button><button class="icon-button" data-project-action="close-picker" title="关闭" aria-label="关闭">${i('x')}</button></div>`;}
  function detail(p){
    if(draft)return editor();
    if(!p)return `<div class="project-empty">${i('folder-kanban')}<h2>${loaded?'暂无项目':'正在加载项目'}</h2><button class="primary" data-project-action="new">${i('plus')}新建项目</button></div>`;
    const linked=tasks(p),done=linked.filter(t=>t.completed).length,percent=linked.length?Math.round(done/linked.length*100):0;
    return `<header class="project-detail-head"><div><span class="project-eyebrow">${p.archived?'已归档':'进行中'}</span><h2>${e(p.name)}</h2><p>${e(p.description)}</p></div><div class="project-actions"><button class="icon-button" data-project-action="edit" title="编辑项目" aria-label="编辑项目">${i('pencil')}</button><button class="icon-button" data-project-action="archive" title="${p.archived?'恢复项目':'归档项目'}" aria-label="${p.archived?'恢复项目':'归档项目'}">${i(p.archived?'archive-restore':'archive')}</button></div></header>
    <div class="project-progress"><div><strong>${done} / ${linked.length}</strong><span>任务完成</span></div><progress max="100" value="${percent}" aria-label="项目完成进度"></progress><span>${percent}%</span></div>
    <div class="project-quick-actions"><button class="primary" data-project-chat="${p.id}" ${p.archived?'disabled':''}>${i('message-square')}在项目中对话</button><button class="secondary" data-action="add" ${p.archived?'disabled':''}>${i('plus')}新建任务</button><button class="secondary" data-project-action="share" ${busy?'disabled':''}>${i('paperclip')}附加项目上下文</button></div>${linkPicker(p)}
    <section class="project-resource-section"><div class="section-head"><h3>任务与时间安排</h3><button class="text-button" data-project-action="pick-task" ${p.archived?'disabled':''}>${i('link')}关联任务</button></div>${linked.map(t=>`<div class="project-task">${context.taskRow(t)}<button class="icon-button" data-project-unlink="${t.id}" data-kind="task" title="取消关联" aria-label="取消关联 ${e(t.title)}" ${p.archived?'disabled':''}>${i('unlink')}</button></div>`).join('')||'<p class="project-empty-line">暂无关联任务</p>'}</section>
    <section class="project-resource-section"><div class="section-head"><h3>项目资料</h3><button class="text-button" data-project-action="pick-document" ${p.archived?'disabled':''}>${i('link')}关联文档</button></div>${p.documents.map(d=>`<div class="project-document"><button data-project-document="${d.id}">${i('file-text')}<span>${e(d.name)}</span><small>v${d.version}</small>${i('arrow-up-right')}</button><button class="icon-button" data-project-unlink="${d.id}" data-kind="document" title="取消关联" aria-label="取消关联 ${e(d.name)}" ${p.archived?'disabled':''}>${i('unlink')}</button></div>`).join('')||'<p class="project-empty-line">暂无关联文档</p>'}</section>`;
  }
  function panel(){const visible=items.filter(p=>p.archived===archived&&(p.name+' '+p.description).toLowerCase().includes(query.toLowerCase()));return `<div class="page-header"><div><h1>工作空间</h1></div><div class="project-actions"><button class="icon-button" data-project-action="refresh" title="刷新项目" aria-label="刷新项目" ${busy?'disabled':''}>${i('refresh-cw')}</button><button class="primary" data-project-action="new" ${busy?'disabled':''}>${i('plus')}新建项目</button></div></div>${error?`<div class="project-error" role="alert">${e(error)}</div>`:''}<div class="project-layout" aria-busy="${busy}"><aside class="project-library"><label class="project-search">${i('search')}<input id="project-query" value="${e(query)}" placeholder="搜索项目" aria-label="搜索项目"></label><div class="project-filters"><button data-project-filter="active" aria-pressed="${!archived}">进行中</button><button data-project-filter="archived" aria-pressed="${archived}">已归档</button></div><div class="project-list">${visible.map(p=>`<button data-project-open="${p.id}" aria-current="${p.id===selected?'true':'false'}"><span>${i('folder')}<strong>${e(p.name)}</strong></span><small>${tasks(p).filter(t=>t.completed).length} / ${p.taskIds.length} · ${p.documents.length} ${e('份资料')}</small></button>`).join('')||'<p class="project-empty-line">没有匹配项目</p>'}</div></aside><div class="project-detail">${detail(current())}</div></div>`;}
  function discard(){return !draft||confirm('放弃未保存的项目修改？');}
  document.addEventListener('input',event=>{const el=event.target;if(el.dataset.projectField&&draft)draft[el.dataset.projectField]=el.value;if(el.id==='project-query'){const pos=el.selectionStart;query=el.value;context.render();const next=document.querySelector('#project-query');next?.focus({preventScroll:true});next?.setSelectionRange(pos,pos);}});
  document.addEventListener('click',async event=>{
    const b=event.target.closest('[data-workspace-view],[data-project-action],[data-project-open],[data-project-filter],[data-project-unlink],[data-project-document]');if(!b||busy)return;
    const action=b.dataset.projectAction,version=epoch;let p=current();
    if(['reload-draft','rebase'].includes(action)&&draft){const remote=items.find(v=>v.id===draft.id);if(!remote)return;if(action==='reload-draft'){if(!discard())return;draft={id:remote.id,version:remote.version,name:remote.name,description:remote.description,archived:remote.archived};}else{if(!confirm('保留我的名称和说明，下次保存将覆盖所示服务器文字，继续？'))return;draft={...draft,version:remote.version,archived:remote.archived};}conflict=false;error='';context.render();return;}
    if(b.dataset.workspaceView){context.state.workspaceView=b.dataset.workspaceView;context.render();return;}
    if(b.dataset.projectOpen){if(!discard())return;context.state.page='workspace';context.state.workspaceView='projects';archived=false;selected=b.dataset.projectOpen;draft=null;picker=null;conflict=false;error='';context.render();return;}
    if(b.dataset.projectFilter){if(!discard())return;archived=b.dataset.projectFilter==='archived';selected=items.find(v=>v.archived===archived)?.id;draft=null;picker=null;conflict=false;error='';context.render();return;}
    if(action==='new'){if(!discard())return;conflict=false;draft={id:crypto.randomUUID(),version:0,name:'',description:'',archived:false};error='';context.render();document.querySelector('[data-project-field=name]')?.focus();return;}
    if(action==='edit'&&p){conflict=false;error='';draft={id:p.id,version:p.version,name:p.name,description:p.description,archived:p.archived};context.render();return;}
    if(action==='cancel'){if(discard()){draft=null;conflict=false;error='';context.render();}return;}
    if(action==='close-picker'){picker=null;context.render();return;}
    const resource=document.querySelector('#project-resource')?.value;
    busy=true;error='';context.render();
    try{
      if(action==='save'){const body={...draft};await context.api('/projects',{method:'POST',body});if(version!==epoch)return;selected=body.id;archived=body.archived;draft=null;conflict=false;await load();context.notify('项目已保存');}
      if(action==='refresh')await load();
      if(action==='archive'&&p&&confirm(p.archived?'恢复此项目？':'归档项目不会删除关联任务和文档，继续？')){await context.api('/projects',{method:'POST',body:{id:p.id,version:p.version,name:p.name,description:p.description,archived:!p.archived}});if(version!==epoch)return;archived=!p.archived;await load();}
      if(action==='pick-task')picker='task';
      if(action==='pick-document'){const result=await context.api('/documents');if(version!==epoch)return;docs=result.documents;picker='document';}
      if(action==='link'&&resource&&p){await context.api(`/projects/${p.id}/links`,{method:'POST',body:{version:p.version,kind:picker,resourceId:resource,linked:true}});if(version!==epoch)return;picker=null;await load();}
      if(b.dataset.projectUnlink&&p&&confirm('仅取消项目关联，不删除原始内容，继续？')){await context.api(`/projects/${p.id}/links`,{method:'POST',body:{version:p.version,kind:b.dataset.kind,resourceId:b.dataset.projectUnlink,linked:false}});await load();}
      if(b.dataset.projectDocument)await window.HermesDocuments.openFromProject(b.dataset.projectDocument);
      if(action==='share'&&p&&confirm('将项目说明、关联任务和文档名称附加给 Hermes？不包含文档正文，也不会自动发送。')){
        const content=JSON.stringify({source:'Hermes Workbench',capturedAt:new Date().toISOString(),readOnly:true,project:{id:p.id,name:p.name,description:p.description},tasks:tasks(p),documents:p.documents},null,2);
        if(await window.HermesChat.attachDocument({name:'project-context.json',content}))context.notify('项目上下文已附加，发送前可预览');
      }
    }catch(cause){if(version===epoch){error=cause.message;if(cause.code==='PROJECT_CONFLICT'){try{await load();if(version===epoch)conflict=Boolean(draft);}catch{}}}}
    finally{if(version===epoch){busy=false;context.render();}}
  });
  window.addEventListener('beforeunload',event=>{if(draft){event.preventDefault();event.returnValue='';}});
  const overview=()=>items.filter(p=>!p.archived).map(p=>({id:p.id,name:p.name,total:tasks(p).length,completed:tasks(p).filter(t=>t.completed).length}));
  return {configure,reset,load,panel,tabs,overview,activeId:()=>context.state.page==='workspace'&&context.state.workspaceView!=='documents'&&!draft&&!current()?.archived?current()?.id:undefined,dirty:()=>Boolean(draft)};
})();
